lib/tracker_web/router.ex
defmodule TrackerWeb.Router do
  use TrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

   def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
 
  
  scope "/", TrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/home", PageController, :userhome
    resources "/users", UserController
    get "/taskdetails/time", TaskTrackersController, :editime
    resources "/taskdetails", TaskTrackersController
    get "/tasks", PageController, :tasks
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  scope "api/v1", TrackerWeb do
    pipe_through :api
    resources "/timeblocks", TimeBlockController, except: [:new, :edit]
    put "/timeblocks", TimeBlockController, :update
    delete "/timeblocks", TimeBlockController, :delete
    post "/timeblocks/delete", TimeBlockController, :delete
    post "/timeblocks/update", TimeBlockController, :updatetime
  end
  # Other scopes may use custom stacks.
  # scope "/api", TrackerWeb do
  #   pipe_through :api
  # end
end

lib/tracker_web/templates/page/index.html.eex
<%= if @current_user do %>
	<div class="row">
		<div class="col">
			<h2> Welcome To Task Tracker</h2>
			<p> Please use the navigation links to explore the application</p>
		</div>
	</div>
<%= else %>
<div class="row">
  <div class="col">
  <h1>Tracker User: Log In</h1>
    <!-- session_path(@conn, :create) -->
    <%= form_tag("/session", method: :post) do %>
      <div class="form-group">
        Enter Email or Name
        <input type="text" name="email" >
      </div>
      <!-- passwords come later -->
      <div class="form-group">
        <button class="btn btn-primary">Log in</button>
        <%= link "Register", to: user_path(@conn, :new) %>
      </div>
    <% end %>
  </div>
</div>
<% end %>

lib/tracker_web/templates/page/tasks.html.eex
<% if @current_user do %>
  <div class="row">
    <div class="col">
    	<%= render TrackerWeb.TaskTrackersView, "form.html", Map.put(assigns, :action, task_trackers_path(@conn, :create)) %>
    </div>
  </div>
<% end %>

<h1> Your Tasks </h1>

<%= Enum.map @mytasks, fn task -> %>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h6 class="card-title"><%= task.title %></h6>
        <p><%= task.desciption %></p>
      </div>
    </div>
  </div>
</div>
<% end %>

lib/tracker_web/templates/page/userhome.html.eex
<%= if @current_user do %>
<div class="row">
	<h2> Welcome <%= @current_user.name %></h2>
</div>
<div class="row">
	<div class="col-3">
		<ul>
			<li> My Tasks </li>
			<li> Details </li>
		</ul>
	</div>
</div>
<% else %>
	<h2 style="color:red"> Login</h2>
<% end %>